OPENAI_API_KEY = "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"
JAI_API_KEY = "kai-bmF0aHJ1amFfc2VuaW9ycGo6dF8tZzhkZC10UlVfVTRERU9kSVpISmg1dnJwNHNrTlNaRWhvTjVaUjliSHYwTXc0bHZtNTR4OEhqLXZkV1h4Ug=="
CHAT_BASE_URL = "https://jai.jts.co.th/v1"
