OPENAI_API_KEY='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'
JAI_API_KEY='kai-bmF0aHJ1amFfc2VuaW9ycGo6dF8tZzhkZC10UlVfVTRERU9kSVpISmg1dnJwNHNrTlNaRWhvTjVaUjliSHYwTXc0bHZtNTR4OEhqLXZkV1h4Ug=='
CHAT_BASE_URL='https://jai.jts.co.th/v1'